
# 配置数据源
spring:
  application:
    name: mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/translate-api?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
# mybatis 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志实现类
    map-underscore-to-camel-case: true                     # 驼峰转换
  type-aliases-package: com.shm.entity                     # 实体类型别名